--1
DROP VIEW MALE_STUDENT;
CREATE VIEW MALE_STUDENT AS (
  SELECT STU_TABLE.SNO, STU_TABLE.SNAME,
    GRADE_TABLE.CNAME, GRADE_TABLE.GRADE
  FROM FUOOKAMI.S STU_TABLE
    LEFT OUTER JOIN (
      SELECT SC.SNO, C.CNAME, SC.GRADE
      FROM FUOOKAMI.SC
        LEFT OUTER JOIN FUOOKAMI.C
        ON FUOOKAMI.SC.CNO = FUOOKAMI.C.CNO
      ) GRADE_TABLE
    ON STU_TABLE.SNO = GRADE_TABLE.SNO
  WHERE STU_TABLE.SGENDER = '男'
);

--2
SELECT DISTINCT SNO, SNAME FROM MALE_STUDENT
  WHERE SNO IN (
    SELECT SNO FROM MALE_STUDENT
    GROUP BY SNO
    HAVING AVG(GRADE) > 80
  );