--1
SELECT S.SNO, S.SNAME FROM FUOOKAMI.S
  WHERE S.SNO IN (
    SELECT DISTINCT SNO FROM FUOOKAMI.SC
    WHERE CNO = '1'
  );

--2
SELECT S.SNO, S.SNAME FROM FUOOKAMI.S
  WHERE S.SNO IN (
    SELECT DISTINCT SNO FROM FUOOKAMI.SC
    WHERE CNO = (
      SELECT CNO FROM FUOOKAMI.C
      WHERE CNAME = '数据结构'
    )
  );

--3
SELECT S.SNO, S.SNAME FROM FUOOKAMI.S
  WHERE S.SNO NOT IN (
    SELECT DISTINCT SNO FROM FUOOKAMI.SC
    WHERE CNO = '1'
  );

--4
SELECT S.SNAME, S.SNO FROM FUOOKAMI.S
  WHERE NOT EXISTS(
    SELECT * FROM FUOOKAMI.C
    WHERE NOT EXISTS(
      SELECT * FROM FUOOKAMI.SC
      WHERE SC.SNO = S.SNO AND SC.CNO = C.CNO
    )
  );

--5 SELECT STUDENT FIT IN
SELECT * FROM (
  SELECT SC.SNO, AVG(SC.GRADE) AS AVG_GRADE
  FROM FUOOKAMI.SC GROUP BY SC.SNO
  HAVING SC.SNO NOT IN (
    SELECT S.SNO FROM S
    WHERE S.SNO IN(
      SELECT DISTINCT SC.SNO FROM SC
      WHERE SC.GRADE < 60 AND CNO != '1'
    )
  )
) ORDER BY AVG_GRADE;

--5 SELECT ALL STUDENT
SELECT S.SNO, AVG_GRADE_TABLE.AVG_GRADE FROM (
  SELECT SC.SNO, AVG(SC.GRADE) AS AVG_GRADE
  FROM FUOOKAMI.SC GROUP BY SC.SNO
  HAVING SC.SNO NOT IN (
    SELECT S.SNO FROM S
    WHERE S.SNO IN(
      SELECT DISTINCT SC.SNO FROM SC
      WHERE SC.GRADE < 60 AND CNO != '1'
    )
  )
) AVG_GRADE_TABLE RIGHT JOIN FUOOKAMI.S
ON AVG_GRADE_TABLE.SNO = FUOOKAMI.S.SNO
ORDER BY AVG_GRADE;

--6
SELECT S.SNAME FROM FUOOKAMI.S
  WHERE S.SNO IN (
    SELECT SC.SNO FROM FUOOKAMI.SC
    WHERE SC.GRADE = (
      SELECT * FROM (
        SELECT DISTINCT SC.GRADE FROM FUOOKAMI.SC
        WHERE SC.CNO = (
          SELECT C.CNO FROM FUOOKAMI.C
          WHERE C.CNAME = '数据库'
        ) ORDER BY SC.GRADE
      ) WHERE ROWNUM = 2
    )
  );

--7
SELECT S.SNAME FROM FUOOKAMI.S
  WHERE S.SNO IN (
    SELECT SC.SNO FROM FUOOKAMI.SC
    WHERE SC.GRADE >= 80 AND SC.CNO IN (
      SELECT C.CNO
      FROM FUOOKAMI.C
      WHERE C.CCREDIT = 3.0
    )
    GROUP BY SC.SNO
    HAVING COUNT(*) >= 3
  );

--8
SELECT S.SNAME FROM FUOOKAMI.S
  WHERE S.SNO IN (
    SELECT SC.SNO FROM FUOOKAMI.SC
    GROUP BY SC.SNO
    HAVING COUNT(*) = 1
  );