DROP TABLE FUOOKAMI.SC;
DROP TABLE FUOOKAMI.C;
DROP TABLE FUOOKAMI.S;

CREATE TABLE FUOOKAMI.S(
  SNO varchar2(10) NOT NULL PRIMARY KEY,
  SName nvarchar2(20) NOT NULL,
  SGender nvarchar2(4) NOT NULL CHECK (SGender = '男' OR SGender = '女'),
  SAge INTEGER NOT NULL CHECK (SAge > 0 AND SAge < 150),
  SDept nvarchar2(64) NOT NULL
);

CREATE TABLE FUOOKAMI.C(
  CNO varchar2(10) NOT NULL PRIMARY KEY,
  CName nvarchar2(64) NOT NULL,
  CPNO varchar2(10),
  CCredit Numeric(4, 2) NOT NULL
);

CREATE TABLE FUOOKAMI.SC(
  SNO varchar2(10) NOT NULL REFERENCES FUOOKAMI.S(SNO),
  CNO varchar2(10) NOT NULL REFERENCES FUOOKAMI.C(CNO),
  Grade INTEGER NOT NULL CHECK (Grade <= 100 AND Grade >= 0)
);

CREATE TRIGGER CHECK_CPNO_IS_A_CNO BEFORE INSERT ON FUOOKAMI.C
FOR EACH ROW
  DECLARE
    num INTEGER;
  BEGIN
    SELECT COUNT(CNO) INTO num FROM FUOOKAMI.C WHERE CNO = :NEW.CPNO;
    IF (:NEW.CPNO IS NOT NULL AND num = 0) THEN
      raise_application_error(-20001, '先行课程不为空且不存在该课程，不允许插入此数据');
    END IF;
  END;